import { sql } from "drizzle-orm";
import * as schema from "./schema";

type Db = import("drizzle-orm/postgres-js").PostgresJsDatabase<typeof schema>;

/**
 * Seed data carried over from the live h06rentals.com platform
 * (fleet, rates, add-ons and interstate surcharges extracted from the
 * production booking engine on 2026-07-08).
 */
export async function seedIfEmpty(db: Db) {
  const existing = await db.select({ n: sql<number>`count(*)` }).from(schema.vehicles);
  if (Number(existing[0]?.n ?? 0) > 0) return;

  await db.insert(schema.vehicles).values([
    {
      slug: "prado_2020",
      name: "Toyota Land Cruiser Prado 2020",
      year: "2020",
      category: "suv",
      tier: "core",
      tagline: "Reliable luxury SUV for city and interstate travel",
      description:
        "The workhorse of Lagos executive travel. Quiet, composed and commanding — the Prado 2020 handles Victoria Island traffic and interstate expressways with equal ease.",
      features: ["7 Seats", "Leather Interior", "Climate Control", "Reverse Camera"],
      seats: 7,
      baggageCapacity: 4,
      excessLuggageCharge: 10000,
      bestFor: ["Airport transfers", "Corporate movement", "Interstate travel"],
      sortOrder: 10,
    },
    {
      slug: "prado_2022",
      name: "Toyota Land Cruiser Prado 2022",
      year: "2022",
      category: "suv",
      tier: "core",
      tagline: "Premium SUV with enhanced comfort and safety features",
      description:
        "The refreshed Prado adds a premium sound system, sunroof and 360° camera to an already formidable executive package.",
      features: ["7 Seats", "Premium Sound", "Sunroof", "360° Camera"],
      seats: 7,
      baggageCapacity: 4,
      excessLuggageCharge: 10000,
      bestFor: ["Executive chauffeur", "Corporate movement", "Events"],
      sortOrder: 20,
    },
    {
      slug: "gx460_2020",
      name: "Lexus GX460 2020",
      year: "2020",
      category: "luxury",
      tier: "core",
      tagline: "Executive luxury SUV — Mark Levinson audio, adaptive suspension",
      description:
        "Lexus refinement with true presence. Mark Levinson audio and adaptive suspension make every journey feel first class.",
      features: ["7 Seats", "Mark Levinson Audio", "Adaptive Suspension", "Leather Interior"],
      seats: 7,
      baggageCapacity: 4,
      excessLuggageCharge: 10000,
      bestFor: ["VIP movement", "Weddings & occasions", "Executive chauffeur"],
      sortOrder: 30,
    },
    {
      slug: "gx460_2022",
      name: "Lexus GX460 2022",
      year: "2022",
      category: "luxury",
      tier: "core",
      tagline: "Latest GX460 — refined luxury with commanding presence",
      description:
        "The flagship of our instant-booking fleet. Ventilated seats, 360° camera, and the quiet confidence Lagos expects of a Lexus.",
      features: ["7 Seats", "Mark Levinson Audio", "Ventilated Seats", "360° Camera"],
      seats: 7,
      baggageCapacity: 4,
      excessLuggageCharge: 10000,
      bestFor: ["VIP movement", "Weddings & occasions", "High-profile guests"],
      sortOrder: 40,
    },
    {
      slug: "hilux_2022",
      name: "Toyota Hilux 2022 V6 XR5",
      year: "2022",
      category: "pickup",
      tier: "core",
      tagline: "Rugged V6 performance — ideal for security and logistics operations",
      description:
        "A V6 Hilux built for escort, security and logistics work. Heavy-duty capability with a professional crew cab.",
      features: ["5 Seats", "V6 Engine", "4WD", "Heavy Duty"],
      seats: 5,
      baggageCapacity: 3,
      excessLuggageCharge: 10000,
      bestFor: ["Security escort", "Logistics", "Interstate support"],
      sortOrder: 50,
    },
    // ── VIP wing (concierge-priced) ──────────────────────────────
    {
      slug: "lx600",
      name: "Lexus LX600",
      year: "2023",
      category: "exotic",
      tier: "vip",
      tagline: "The flagship Lexus — executive travel redefined",
      description: "The pinnacle of Lexus luxury. Priced and prepared by our concierge for each engagement.",
      features: ["Flagship Luxury", "Rear Executive Seating", "Mark Levinson Audio"],
      seats: 5,
      bestFor: ["Heads of state & C-suite", "High-profile arrivals"],
      sortOrder: 110,
    },
    {
      slug: "lx570",
      name: "Lexus LX570",
      year: "2022",
      category: "exotic",
      tier: "vip",
      tagline: "Full-size luxury SUV with commanding road presence",
      features: ["Full-size Luxury", "Commanding Presence"],
      seats: 7,
      bestFor: ["VIP convoys", "Executive travel"],
      sortOrder: 120,
    },
    {
      slug: "gwagon_2023",
      name: "Mercedes-Benz G-Wagon 2023",
      year: "2023",
      category: "exotic",
      tier: "vip",
      tagline: "The icon. Unmistakable, uncompromising",
      features: ["Iconic Design", "Statement Arrival"],
      seats: 5,
      bestFor: ["Statement arrivals", "Music & entertainment", "Weddings"],
      sortOrder: 130,
    },
    {
      slug: "landcruiser_2022",
      name: "Toyota Land Cruiser 2022",
      year: "2022",
      category: "exotic",
      tier: "vip",
      tagline: "Legendary off-road capability meets executive comfort",
      features: ["Legendary Capability", "Executive Comfort"],
      seats: 7,
      bestFor: ["Interstate convoys", "Executive travel"],
      sortOrder: 140,
    },
    {
      slug: "landcruiser_2024",
      name: "Toyota Land Cruiser 2024",
      year: "2024",
      category: "exotic",
      tier: "vip",
      tagline: "New generation Land Cruiser — power, prestige, performance",
      features: ["New Generation", "Prestige"],
      seats: 7,
      bestFor: ["Prestige movement", "Long-range travel"],
      sortOrder: 150,
    },
    {
      slug: "prado_2025",
      name: "Toyota Prado 2025",
      year: "2025",
      category: "exotic",
      tier: "vip",
      tagline: "The all-new Prado — first of its kind in Lagos",
      features: ["All-new Design", "Latest Technology"],
      seats: 7,
      bestFor: ["First impressions", "Corporate flagships"],
      sortOrder: 160,
    },
    {
      slug: "range_rover",
      name: "Range Rover",
      year: "—",
      category: "exotic",
      tier: "vip",
      tagline: "British luxury, Lagos presence",
      features: ["British Luxury"],
      seats: 5,
      bestFor: ["Weddings", "VIP arrivals"],
      sortOrder: 170,
    },
    {
      slug: "rolls_royce",
      name: "Rolls-Royce",
      year: "—",
      category: "exotic",
      tier: "vip",
      tagline: "The ultimate arrival",
      features: ["Ultimate Luxury"],
      seats: 4,
      bestFor: ["Weddings", "Once-in-a-lifetime moments"],
      sortOrder: 180,
    },
    {
      slug: "urus",
      name: "Lamborghini Urus",
      year: "—",
      category: "exotic",
      tier: "vip",
      tagline: "Super-SUV performance",
      features: ["Super-SUV"],
      seats: 4,
      bestFor: ["Statement occasions"],
      sortOrder: 190,
    },
    {
      slug: "armoured",
      name: "Armoured Vehicles",
      year: "—",
      category: "exotic",
      tier: "vip",
      tagline: "Discreet certified protection for security-conscious movement",
      features: ["Certified Armour", "Discreet Protection"],
      seats: 5,
      bestFor: ["Security-conscious movement", "High-risk itineraries"],
      sortOrder: 200,
    },
    {
      slug: "luxury_bus",
      name: "Luxury Buses",
      year: "—",
      category: "bus",
      tier: "vip",
      tagline: "Group movement without compromise",
      features: ["Group Travel", "Executive Interior"],
      seats: 14,
      bestFor: ["Corporate groups", "Event logistics", "Wedding parties"],
      sortOrder: 210,
    },
  ]);

  await db.insert(schema.vehicleRates).values([
    { vehicleSlug: "prado_2020", airportTransfer: 125000, twelveHours: 170000, twentyFourHours: 300000, multiDayDaily: 300000, interstateBase: 170000, interstateChauffeur: 80000 },
    { vehicleSlug: "prado_2022", airportTransfer: 125000, twelveHours: 250000, twentyFourHours: 450000, multiDayDaily: 450000, interstateBase: 250000, interstateChauffeur: 80000 },
    { vehicleSlug: "gx460_2020", airportTransfer: 150000, twelveHours: 300000, twentyFourHours: 550000, multiDayDaily: 550000, interstateBase: 300000, interstateChauffeur: 100000 },
    { vehicleSlug: "gx460_2022", airportTransfer: 150000, twelveHours: 350000, twentyFourHours: 600000, multiDayDaily: 600000, interstateBase: 350000, interstateChauffeur: 100000 },
    { vehicleSlug: "hilux_2022", airportTransfer: 100000, twelveHours: 150000, twentyFourHours: 250000, multiDayDaily: 250000, interstateBase: 150000, interstateChauffeur: 70000 },
  ]);

  await db.insert(schema.addOns).values([
    { slug: "meet_greet", label: "Meet & Greet", description: "Driver meets you at arrivals with a name board", priceNgn: 15000, sortOrder: 10 },
    { slug: "vip_airport_protocol", label: "VIP Airport Protocol", description: "Dedicated personal assistant — fast-track through all airport processes", priceNgn: 100000, sortOrder: 20 },
    { slug: "chauffeur_spy_police", label: "Spy Police Chauffeur Upgrade", description: "Certified police officer with security training — ideal for high-profile travel", priceNgn: 20000, sortOrder: 30 },
    { slug: "security_escort", label: "Security Escort", description: "Fully kitted MOPOL escort vehicle — rates vary by region", priceNgn: null, sortOrder: 40 },
    { slug: "extra_driver", label: "Extra Driver", description: "Second driver for extended or relay trips", priceNgn: null, sortOrder: 50 },
    { slug: "visa_on_arrival", label: "Visa on Arrival Assistance", description: "Dedicated support for visa-on-arrival processing at MMIA", priceNgn: null, sortOrder: 60 },
  ]);

  await db.insert(schema.interstateSurcharges).values([
    { state: "Ogun", region: "South West", surcharge: "0.35" },
    { state: "Oyo", region: "South West", surcharge: "0.38" },
    { state: "Osun", region: "South West", surcharge: "0.40" },
    { state: "Ondo", region: "South West", surcharge: "0.42" },
    { state: "Ekiti", region: "South West", surcharge: "0.45" },
    { state: "Edo", region: "South South", surcharge: "0.50" },
    { state: "Delta", region: "South South", surcharge: "0.55" },
    { state: "Bayelsa", region: "South South", surcharge: "0.60" },
    { state: "Rivers", region: "South South", surcharge: "0.62" },
    { state: "Akwa Ibom", region: "South South", surcharge: "0.65" },
    { state: "Cross River", region: "South South", surcharge: "0.70" },
    { state: "Anambra", region: "South East", surcharge: "0.50" },
    { state: "Imo", region: "South East", surcharge: "0.55" },
    { state: "Enugu", region: "South East", surcharge: "0.58" },
    { state: "Abia", region: "South East", surcharge: "0.60" },
    { state: "Ebonyi", region: "South East", surcharge: "0.65" },
    { state: "Kwara", region: "North Central", surcharge: "0.65" },
    { state: "Kogi", region: "North Central", surcharge: "0.68" },
    { state: "Benue", region: "North Central", surcharge: "0.70" },
    { state: "Abuja", region: "North Central", surcharge: "0.75" },
  ]);

  await db.insert(schema.settings).values([
    { key: "whatsapp_number", value: "2349139999533" },
    { key: "business_email", value: "hello@h06rentals.com" },
    { key: "deposit_percent", value: "50" },
    { key: "bank_transfer_details", value: "Account details are shared by our concierge on WhatsApp after booking." },
  ]);
}
